package com.phrasenest.expression.domain;


/**
 * Indicates where an expression record came from.
 */
public enum SourceType {

    /**
     * Created manually by an administrator or editor.
     */
    EDITORIAL,

    /**
     * Generated by an LLM.
     */
    AI_GENERATED,

    /**
     * Submitted by an application user.
     */
    COMMUNITY_SUBMITTED,

    /**
     * Imported from an approved dataset.
     */
    IMPORTED
}
